### ISSUE TITLE
Repeated dependencies in the JSON file

### ISSUE THREAD

**Issue by ghost** [icetan/mavenix#10]
The generated JSON file has many redundant copies of the same plugins. In particular, the generated JSON file for one of my packages has 2200 lines. Is this expected behavior, or can this be avoided?

Example:

```
    {"path":"antlr/antlr/2.7.2/antlr-2.7.2.pom","sha1":"60b2b206af3df735765e8e284396bcfdbced5665"},
    {"path":"antlr/antlr/2.7.2/antlr-2.7.2.jar","sha1":"546b5220622c4d9b2da45ad1899224b6ce1c8830"},
    {"path":"antlr/antlr/2.7.6/antlr-2.7.6.jar","sha1":"cf4f67dae5df4f9932ae7810f4548ef3e14dd35e"},
    {"path":"antlr/antlr/2.7.6/antlr-2.7.6.pom","sha1":"1ef68a00c22016097c813d1aae66fdd486e34c74"},
    {"path":"antlr/antlr/2.7.7/antlr-2.7.7.jar","sha1":"83cd2cd674a217ade95a4bb83a8a14f351f48bd0"},
    {"path":"antlr/antlr/2.7.7/antlr-2.7.7.pom","sha1":"52f15b99911ab8b8bc8744675f5cf1994a626fb8"},
```

**Comment by icetan** [comment]
The way Mavenix works is it runs Maven and looks in the resulting repository that Maven created and generates a JSON from the contents.

So, the question is: why does Maven download all those duplicates?

You can try removing duplicates from the JSON manually and then run `nix-build`. If it still builds I can try to figure out if there is a way to get a slimmer JSON.

I can also try to look at your project if you have a link or something.

**Comment by ghost** [comment]
I just tested, and removing any JAR from the list makes the compilation to fail. It seems that Maven just works like that.

Thank you very much!
