### ISSUE TITLE
Pass options to mvn package command

### ISSUE THREAD

**Issue by ttuegel** [icetan/mavenix#11]
Building my project under Nix requires some options to be passed to the `mvn package` command during build. I can edit the generated `mavenix.nix` file to do that, but I cannot run `mvnix-update`. I can work around this by adding the options to `mvnix-update`, but it would be useful to pass options through that script.

**Comment by icetan** [comment]
Have you tried setting `MAVEN_OPTS` when calling `mavenix`? E.g. `mavenix { MAVEN_OPTS = "-Dsome=stuff -otherflags"; ... }` in `default.nix`.

The attributes passed to `mavenix` get passed on to the underlying `mkDerivation`, therefore you can set any environment variable this way.

This will also help you when running `mvnix-update` as `MAVEN_OPTS` will be set when inside a `nix-shell`. Just make sure your `.bashrc` or the like doesn't override it.

I realise this isn't mentioned in the docs and that `nix-shell` isn't either, I will try to fix that. I still haven't settled on a robust workflow.

**Comment by ttuegel** [comment]
This works, but it should be noted that the `MAVEN_OPTS` syntax is inexplicably different from the command-line syntax. For example, `MAVEN_OPTS="-DskipTests"` does not work, but `MAVEN_OPTS="-DskipTests=true"` does.

**Comment by icetan** [comment]
> This works, but it should be noted that the `MAVEN_OPTS` syntax is inexplicably different from the command-line syntax. For example, `MAVEN_OPTS="-DskipTests"` does not work, but `MAVEN_OPTS="-DskipTests=true"` does.

`MAVEN_OPTS` is actually just an environment variable that is picked up directly by `mvn` and not a feature of `mavenix`. So yeah, Maven is weird :smile:

**Comment by ttuegel** [comment]
> So yeah, Maven is weird

Oh, absolutely! :smile: I didn't mean this as an accusation, just a note for the next person who has this issue. (If we're being honest, that's *me* in another three months probably.)
