### ISSUE TITLE
`mvnix-update` uses `.override` which blocks the use of `callPackage`

### ISSUE THREAD

**Issue by FRidh** [icetan/mavenix#18]
Consider the file `builder.nix`
```
{ mavenix, ... }:

mavenix.buildMaven {
...
}
```
and 
```
{
  foo = callPackage ./builder { };
}
```
Using `mvnix-update -E "(import ./.).foo"` will fail because `.override` is redefined by `callPackage`. This is a common issue, and can be worked around by the user, however, I think it would be better if `buildMaven` defines an `overrideAttrs` instead. 

For Python I introduced at the time `overridePythonAttrs`, but in retrospect I think all specific builders should re-define `overrideAttrs`. See also https://github.com/NixOS/nixpkgs/pull/46842#issuecomment-451480872.

**Comment by icetan** [comment]
Something like this #19?

**Comment by FRidh** [comment]
This has been fixed.
