### ISSUE TITLE
Add JDK to buildInputs?

### ISSUE THREAD

**Issue by FRidh** [icetan/mavenix#20]
To improve the `nix-shell` experience I think it would be good to add the JDK to `buildInputs`. 
Unfortunately the `maven` expression currently does not add it to the `passthru`, but I think we can make that change in Nixpkgs.

Having the JDK, along with potentially some env variables (such as `JAVA_HOME`) in a `shellHook` should make it easier to develop through Eclipse, although I am not sure yet (just started using Java).

**Comment by icetan** [comment]
We could add `maven.jdk` to `buildInputs` for now?

This will add the correct `JAVA_HOME` to `nix-shell` automatically also!

>    To improve the nix-shell experience I think it would be good to add the
>    JDK to buildInputs.
>    Unfortunately the maven expression currently does not add it to the
>    passthru, but I think we can make that change in Nixpkgs.

Haven't thought about developing this way, but it does sound like a good idea.

The way I develop now is using `javacs` (LSP), where `javacs` is packaged
with `mavenix`. This means that `javacs` is running with it's own version
of JDK. I build separately using `mvn` from within `nix-shell` though so it's not
optimal, but it's not super important that the JDK versions match either.

>    Having the JDK, along with potentially some env variables (such as
>    JAVA_HOME) in a shellHook should make it easier to develop through
>    Eclipse, although I am not sure yet (just started using Java).

**Comment by FRidh** [comment]
Ah, indeed, the jdk is already added. Perfect!
