### ISSUE TITLE
how do i use this with nix pkgs on mac?

### ISSUE THREAD

**Issue by cartazio** [icetan/mavenix#23]
i'm probably overlooking something obvious, but i'm stumped onhow i add/run this in nix on mac. the readme assumes i know more than I do :)

**Comment by cartazio** [comment]
i'm trying running the directions in several different ways and i can't make heads or tails of it :(

**Comment by icetan** [comment]
Hi @cartazio, thank you for showing interest in Mavenix.

I don't currently have access to a MacOS instance but will try to help you as best I can.

First things first, have you managed to install the CLI, i.e. the terminal commands `mvnix-init` and `mvnix-update` by running `nix-env -i -f https://github.com/icetan/mavenix/archive/master.tar.gz`?

**Comment by cartazio** [comment]
```
 nix-env -i -f https://github.com/icetan/mavenix/archive/master.tar.gz --verbose --show-trace
evaluating file '/nix/store/jbwybyljrmfcsiad7mf4z4mp5ykazjgf-nix-2.2/share/nix/corepkgs/derivation.nix'
downloading 'https://github.com/icetan/mavenix/archive/master.tar.gz'...
unpacking 'https://github.com/icetan/mavenix/archive/master.tar.gz'...
evaluating file '/nix/store/wshxiaq02xsjfyah1h60f3czybpzv9sb-master.tar.gz/default.nix'
evaluating file '/nix/store/wshxiaq02xsjfyah1h60f3czybpzv9sb-master.tar.gz/mavenix.nix'
downloading 'https://github.com/NixOS/nixpkgs/archive/18.09.tar.gz'...
unpacking 'https://github.com/NixOS/nixpkgs/archive/18.09.tar.gz'...
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/default.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/minver.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/top-level/impure.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/top-level/default.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/stdenv/booter.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/default.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/fixed-points.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/lists.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/stdenv/default.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/trivial.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/systems/default.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/attrsets.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/systems/inspect.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/systems/parse.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/strings.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/types.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/options.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/stdenv/darwin/default.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/top-level/stage.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/stdenv/adapters.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/build-support/trivial-builders.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/top-level/splice.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/top-level/all-packages.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/top-level/aliases.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/stdenv/generic/default.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/customisation.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/systems/platforms.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/stdenv/generic/make-derivation.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/pkgs/stdenv/generic/check-meta.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/licenses.nix'
evaluating file '/nix/store/iam5nc2mbh7nssw5xji5q54gbnnbvjwb-source/lib/meta.nix'
evaluating file '/nix/store/frhblhr70gsyvkxr0j9hr4yaz0v3s0m8-env-manifest.nix'
evaluating file '/nix/store/jbwybyljrmfcsiad7mf4z4mp5ykazjgf-nix-2.2/share/nix/corepkgs/buildenv.nix'


```

i think one issue i'm possibly hitting is the whole pinned nixpkgs piece instead of the code just inheriting my current nixpkgs? (i have no clue)

as a bit of context, i've a work related project OSS by some colleagues i've been using to stress test different nix things, and https://github.com/jpmorganchase/tessera seems to break the maven plugin approach in maven2nix stuff, so i'd be keen on finding out if mavenix handles the stuff thats not resolved correctly by that tool

**Comment by cartazio** [comment]
i'm currently on the unstable channel of nixpkgs with a DL/update from a few days ago

**Comment by cartazio** [comment]
(i'm worried i'll have to write some sort of haskell tool to parse and solve version info in haskell for all the implicit grotty stuff in eg that example repo and other examkples that might exist, and i'd rather not..)

**Comment by icetan** [comment]
> i think one issue i'm possibly hitting is the whole pinned nixpkgs piece instead of the code just inheriting my current nixpkgs? (i have no clue)

This shouldn't be a problem for installing Mavenix though. Still not sure if you managed to install the `mvnix-init` and `mvnix-update` commands?

> as a bit of context, i've a work related project OSS by some colleagues i've been using to stress test different nix things, and https://github.com/jpmorganchase/tessera seems to break the maven plugin approach in maven2nix stuff, so i'd be keen on finding out if mavenix handles the stuff thats not resolved correctly by that tool

I tried to build Tessera with Mavenix myself and hit on some problems. WIll look into it further and post back.

**Comment by cartazio** [comment]
nope, doesn't install, and when i've tried to use the shell commands 

heres something that might be more informative

```
11:36:13 ~/l/e/i/mavenix (master|✔) $ nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}' --verbose --show-trace -j20
evaluating file '/nix/store/jbwybyljrmfcsiad7mf4z4mp5ykazjgf-nix-2.2/share/nix/corepkgs/derivation.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/default.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/minver.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/top-level/impure.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/top-level/default.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/booter.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/default.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/fixed-points.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/lists.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/default.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/systems/default.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/attrsets.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/systems/inspect.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/trivial.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/systems/parse.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/strings.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/types.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/options.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/systems/platforms.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/modules.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/debug.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/top-level/config.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/darwin/default.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/top-level/stage.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/adapters.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/build-support/trivial-builders.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/top-level/splice.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/top-level/all-packages.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/top-level/aliases.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/generic/default.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/customisation.nix'
evaluating file '/Users/carter/local/enterprise/iin-nix-pkg/mavenix/default.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/servers/x11/xorg/default.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/servers/x11/xorg/overrides.nix'
evaluating file '/Users/carter/local/enterprise/iin-nix-pkg/mavenix/mavenix.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/generic/make-derivation.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/generic/check-meta.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/licenses.nix'
evaluating file '/nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/meta.nix'
error: while evaluating the attribute 'handled' at /nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/generic/check-meta.nix:252:7:
while evaluating 'handleEvalIssue' at /nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/generic/check-meta.nix:146:28, called from /nix/store/1zjkl6z5pymibk49rnmn9gknwdmc750p-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/stdenv/generic/check-meta.nix:253:14:
Package ‘mavenix-2.0.0’ in /Users/carter/local/enterprise/iin-nix-pkg/mavenix/default.nix:87 is not supported on ‘x86_64-apple-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.

```

**Comment by cartazio** [comment]
so something about the way its written assumes i'm using nixos rather than just user space nixpkgs? I"m still learning all the implicit convensions in nix, and I tried tweaking the files a bit but no dice

**Comment by cartazio** [comment]
how do i rewrite 

```
  pkgs ? import (fetcher {
    owner   = "NixOS";
    repo    = "nixpkgs";
    rev     = "18.09";
    sha256  = "1ib96has10v5nr6bzf7v8kw7yzww8zanxgw2qi1ll1sbv6kj6zpd";
  }) {},
}:

``` 
into something that just is "gimme your nixpkgs"

**Comment by cartazio** [comment]
maybe pkgs = import <nixpkgs> {}; ?

**Comment by cartazio** [comment]
platforms = [ "x86_64-linux" ]; 

DERP, you hard coded platform assumptions there ..

**Comment by cartazio** [comment]
ok, summary so far: 

definitly needs to not hard code linux 64 bit if we want it to work on not linux. :)

**Comment by cartazio** [comment]
another issue, when i run this stuff in a directory, perhaps because of the mavenix URL based reference, or because of linuxy bit of bash
```
 $ ../../mavenix/result/bin/mvnix-init -o ./  -S default.nix

  Creating files:

cp: skipping file '/dev/fd/63', as it was replaced while being copied
```

so nothing gets created..

**Comment by cartazio** [comment]
i'm not sure how the source file is meant to be used also ..

**Comment by cartazio** [comment]
I really appreciate your responsiviness.

so theres at least 3 issues

a) hard codes supporting linux only
b) theres some some lack of information/documentaiton about what  about the nix formula / expression inputs needed for `init` and `update`, so i'm possibly just doing something wrong here thats "obvious", but i have no idea what it should be.
c) theres some tricky bits with multi pom projects/repos  (poms that refer to /share data with a parent pom or dep ) and/or extensive use of maven plugins? 

it *looks* like theres been some dev activity on mvn2nix since the last plugin release a few years ago (~4?), so i should poke at that (though a close look suggest it also fails to handle eg build / maven plugins)

**Comment by icetan** [comment]
> so something about the way its written assumes i'm using nixos rather than just user space nixpkgs? I"m still learning all the implicit convensions in nix, and I tried tweaking the files a bit but no dice

This is not the problem, I'm on Arch Linux myself and not running on NixOS.

I think we need to hold of on injecting your `nixpkgs` set for now and just run with the pinned version. Too many parameters to consider otherwise if I'm going to try to help you. We can take a look at that after the basics work.

> a) hard codes supporting linux only

The package meta (`platforms = [ "x86_64-linux" ];`) is set like this because I haven't been able to try Mavenix properly on anything but Linux.

To ignore the `platforms` meta, you can as the output you pasted from installing Mavenix mentions:

```
b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.
```

Will update this if we can make it work on your Mac :)


> b) theres some some lack of information/documentaiton about what about the nix formula / expression inputs needed for init and update, so i'm possibly just doing something wrong here thats "obvious", but i have no idea what it should be.

It might help you to run `mvnix-init --help` and `mvnix-update --help`, they do give some information about the arguments they take at least.


> another issue, when i run this stuff in a directory, perhaps because of the mavenix URL based reference, or because of linuxy bit of bash
> 
> ```
>  $ ../../mavenix/result/bin/mvnix-init -o ./  -S default.nix
> 
>   Creating files:
> 
> cp: skipping file '/dev/fd/63', as it was replaced while being copied
> ```
> so nothing gets created..

Yes, this looks like some bash incompatibility.

Also the `-S` arguments takes a Nix expression to the Java source you want to build, not a path to a `.nix` file.

E.g. to use the parent directory as `src` to the derivation you can do: `mvnix-init -S '../.'` or to reference sources from a git repo directly: `mvnix-init -S 'fetchGit { url = https://github.com/owner/repo; rev = "<commit hash>"; }'`.


> c) theres some tricky bits with multi pom projects/repos (poms that refer to /share data with a parent pom or dep ) and/or extensive use of maven plugins?

I managed to generate a lock file by changing the `mvnix-update` script to do `mvn install` instead of just a `package` which resolved the issue of modules having dependencies on each other in Tessera.

The next problem I ran into though when actually building the derivation was that the `grpc` module has problems executing the `protoc` binary which has the wrong permissions set. This is probably due to that  the binaries are copied from the Nix store where there permissions are set to read-only.

Might be able to fix this in the `preBuild` phase of the derivation. Will look in to this further.

**Comment by icetan** [comment]
I pushed the branch [macos-fixes](https://github.com/icetan/mavenix/tree/macos-fixes) to address MacOS compatibility and will also try to fix issues with Tessera there.

**Comment by icetan** [comment]
> The next problem I ran into though when actually building the derivation was that the `grpc` module has problems executing the `protoc` binary which has the wrong permissions set. This is probably due to that the binaries are copied from the Nix store where there permissions are set to read-only.
> 
> Might be able to fix this in the `preBuild` phase of the derivation. Will look in to this further.

Managed to fix the permission problem by adding a `postMkRepoHook` to `buildMaven`. This hook makes it possible to fix the Nix generated Maven repo before it is added to the Nix store.

This is how I used it for Tessera:

```
  postMkRepoHook = with pkgs; ''
    fix_exe() {
      local tmp_name="./$(basename "$1")"
      cp "$(realpath "$1")" "$tmp_name";
      chmod 755 "$tmp_name"

      ${patchelf}/bin/patchelf --set-interpreter "$(cat "${stdenv.cc}/nix-support/dynamic-linker")" "$tmp_name"

      mv "$tmp_name" "$1"
    }
    export -f fix_exe

    find $out -name "*.exe" -exec sh -c "fix_exe {}" \;
  '';
```

Adding the above to the `default.nix` generated by `mvnix-init` should be enough to successfully build Tessera using the `macos-fixes` branch of Mavenix.

**Comment by cartazio** [comment]
zomg, thx! I'll test this all shortly.

**Comment by cartazio** [comment]
1) getting  a lot of 
```
warning: there are multiple derivations named 'zulu1.8.0_121-8.20.0.5'; using the first one
warning: there are multiple derivations named 
```

also have to set 

```
 { allowUnfree = true; 
  allowUnsupportedSystem = true; }
```

i'll throw a branch online so i can show you the changes i've made / where i'm still breaking it

**Comment by cartazio** [comment]
`    ${patchelf}/bin/patchelf --set-interpreter "$(cat "${stdenv.cc}/nix-support/dynamic-linker")" "$tmp_name"
`
thats definitely linux only :)

**Comment by cartazio** [comment]
i think your remark here should be addded to the docs! :) thats clever, and totally not what i was guessing 

E.g. to use the parent directory as src to the derivation you can do: mvnix-init -S '../.' or to reference sources from a git repo directly: mvnix-init -S 'fetchGit { url = https://github.com/owner/repo; rev = "<commit hash>"; }'.

**Comment by icetan** [comment]
> i'll throw a branch online so i can show you the changes i've made / where i'm still breaking it

Have you had time to try things out yet? I've still not had time myself to find a MacOS instance to test on.

> `${patchelf}/bin/patchelf --set-interpreter "$(cat "${stdenv.cc}/nix-support/dynamic-linker")" "$tmp_name"`
> thats definitely linux only :)

You can skip `patchelf` on Darwin by doing something like:

```
  postMkRepoHook = with pkgs; ''
    fix_exe() {
      local tmp_name="./$(basename "$1")"
      cp "$(realpath "$1")" "$tmp_name";
      chmod 755 "$tmp_name"

      ${lib.optionalString (!stdenv.isDarwin) ''
        ${patchelf}/bin/patchelf --set-interpreter "$(cat "${stdenv.cc}/nix-support/dynamic-linker")" "$tmp_name"
      ''}

      mv "$tmp_name" "$1"
    }
    export -f fix_exe

    find $out -name "*.exe" -exec sh -c "fix_exe {}" \;
  '';
```
