### ISSUE TITLE
Referring to another Mavenix derivation

### ISSUE THREAD

**Issue by FRidh** [icetan/mavenix#24]
I have one library packaged with Mavenix, and now I would like to use it in another library managed with Mavenix, and I am trying to find out how to do this.

First, I pass in `drvs = [ my-dependency ];`. When I now run `mvnix-update`, I can see "building mavenix drvs", however, in the next step, "Running mvn package...", it attempts to fetch the .jar and fails.

**Comment by FRidh** [comment]
I think we need to install `drvs` using https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

**Comment by icetan** [comment]
> I think we need to install `drvs` using https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

The `mkRepo` function in `mavenix.nix` should already take this into consideration and put the output of referenced Mavenix derivations in the right place when creating the Maven repo.

Is it possible for you to show me your code so I can run some tests?

**Comment by FRidh** [comment]
You are correct. The `repo` path contained the paths as expected. I had made a mistake in the POM.
