### ISSUE TITLE
extraNativeBuildInputs is inconsistent

### ISSUE THREAD

**Issue by FRidh** [icetan/mavenix#28]
https://github.com/icetan/mavenix/commit/1a8e1ff002360402f4f29099d2f97f66155c038c added `extraNativeBuildInputs` and broke support for `nativeBuildInputs`. Any specific reason for not permitting `nativeBuildInputs`?

**Comment by FRidh** [comment]
Regarding the title. In `stdenv.mkDerivation` we have many different types of `inputs`, where several are especially important for cross. With builders it's always the question whether they should still offer the same interface (by exposing those) or offer a different interface. I don't know what your ideas are on that regarding Mavenix or in general what makes sense when packaging Java.

**Comment by icetan** [comment]
That was sort of a rash change. It just felt cleaner but as with `passthru` it wasn't properly thought through interface wise.

I will revert the changes and we can continue the discussion in this issue.

**Comment by FRidh** [comment]
I agree having maven in `nativeBuildInputs` though, it's good to consider that now. Have you ever tried cross-compiling Java? I am not interested in it, but I think we should keep it in mind.

**Comment by icetan** [comment]
> Have you ever tried cross-compiling Java? I am not interested in it, but I think we should keep it in mind.

I guess that Java is agnostic to target platform. But as in this issue: https://github.com/icetan/mavenix/issues/23#issuecomment-487858791 there might be other binaries packaged.
