### ISSUE TITLE
`mvnix-update` needs to build the `src` attribute

### ISSUE THREAD

**Issue by FRidh** [icetan/mavenix#31]
In fab82e7e the way the source path is obtained is changed. Previously, `nix-shell` was used. Because the `src` is an actual dependency, the path would be realized. Now, `nix-instantiate` is used, in which case `src` is not necessarily realized. This is noticed when the source is fetched or when the source is filtered.

If the path to the source is needed, then we should always realize it.

**Comment by icetan** [comment]
@FRidh this should fix the problem. Any feedback?
