### ISSUE TITLE
mvnix-update fails because xq could not be found

### ISSUE THREAD

**Issue by RocketPuppy** [icetan/mavenix#7]
I attempted to run `mvnix-update`, and it failed while getting project info with `/nix/store/mjg9ikr0jlsww42mylgcp5kym0jdikg6-mvnix/bin/.mvnix-update-wrapped: line 61: xq: command not found`. I'm assuming the `xq` being referenced is this one https://github.com/syui/xq. If so I can work on trying to get that dependency specified in `default.nix`.

**Comment by icetan** [comment]
It might be that you have an older version of `nixpkgs` than required. I should maybe pin a `nixpkgs` version for the tooling though.

It is weird that the `mavenix` derivation built at all. The package that has the command `xq` is called `yq` (https://github.com/kislyuk/yq) and is a dependency for `mavenix`.

Could you post a copy of your `mvnix-update` wrapper script?

**Comment by RocketPuppy** [comment]
Here's .mvnix-update-wrapped and mvnix-update https://gist.github.com/RocketPuppy/851469628e75b4f05871ae2c53213c78. I'll have more time to look into the dependencies and derivations later today, including working off an updated nixpkgs. I'm still on the 18.03 channel and I haven't updated in a while.

**Comment by icetan** [comment]
OK, so I didn't know `yq` doesn't support `xq` until version 2.4 and your version is 2.3.4. Updating `nixpkgs` should solve it.

I should probably look into pinning a version of `yq`.

**Comment by RocketPuppy** [comment]
Yep, using a newer version of nixpkgs fixed the issue. I'm happy to write a PR to pin the nixpkgs version. My approach would be to add a file like this:
```
let source =
    rec {
      owner = "NixOS";
      repo = "nixpkgs-channels";
      rev = "0a7e258012b60cbe530a756f09a4f2516786d370";
      sha256 = "1qcnxkqkw7bffyc17mqifcwjfqwbvn0vs0xgxnjvh9w0ssl2s036";
      name = "nixpkgs${rev}";
    };
    fetch = (import <nixpkgs> {}).fetchFromGitHub;
in
import (fetch (source))
```
and change the first line of default.nix from `pkgs ? import <nixpkgs> {}` to `pkgs ? import ./nixpkgs.nix {}`. I know it builds with that commit there, but I'm happy to use a different commit if you want.

**Comment by icetan** [comment]
That looks like a good solution. A PR would be great :)
